backend:
  name: github
  repo: "mimecine/dev.atelierromeny.com" # The GitHub repository where the content will be stored
  branch: main

media_folder: "src/media/img"
public_folder: "/src/media/img"

collections:
  - name: "works"
    label: "Works"
    folder: "src/content/works"
    create: true
    slug: "{{id}}-{{title}}-{{year}}"
    summary: "{{title}}, {{year}}, {{location}}"
    identifier_field: "title"
    search_fields: ["title", "id", "year", "location"]
    editor:
      preview: false
    # # sortable fields won't work until all fields are filled  on each item
    # sortable_fields: 
    #   - "title"
    #   - "year"
    #   - "location"
    fields:
      - { label: "ID", name: "id", widget: "number", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Collections", name: "collections", widget: "relation", collection: "collections", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: true, required: false }
      - { label: "Categories", name: "categories", widget: "string", required: false }
      - { label: "Width (cm)", name: "w", widget: "number", required: false }
      - { label: "Height (cm)", name: "h", widget: "number", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Notes", name: "note", widget: "text", required: false }
      # - { label: "File", name: "file", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Year Start", name: "year_start", widget: "number", required: false }
      - { label: "Year End", name: "year_end", widget: "number", required: false }


  - name: "collections"
    label: "Collections"
    folder: "src/content/collections"
    create: true
    slug: "{{title}}"
    identifier_field: "id"
    summary: "{{title}}"
    fields:
      - { label: "ID", name: "id", widget: "uuid", required: true, hidden: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Notes", name: "notes", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "body", widget: "markdown", required: false }
      - { label: "Works", name: "works", widget: "relation", collection: "works", search_fields: ["title","id","year_start","location"], value_field: "id", display_fields: ["title","year_start"], multiple: true, required: false }
  