site_title: Edlef Romeny
menu:
  - title: Bio
    href: /bio
  - title: Paintings
    href: /selected-paintings
  - title: Prints
    href: /selected-prints
  - title: SEARCH
    href: /search
sections:
  - type: image
    title: Image
    show_title: false
    hidden: false
    image: /src/media/assets/Edlef While Painting.webp
    caption: ''
    href: ''
  - type: content
    show_title: false
    columns: 1
    hidden: false
    header: ''
    text: _A Dutchman who painted his way from Antwerp to Stockholm to the Luberon, and never stopped looking for colour..._
barrier:
  enabled: true
  password: edlef
  days: 7
  text: ''
socials:
  - title: '@atelierromeny'
    href: https://www.instagram.com/atelierromeny/
  - title: 'Inquiries: Marco Romeny'
    href: mailto:marco@atelierromeny.com
copyright: The Estate of Edlef Romeny
ga: ''
css: ''
js: ''
collections:
  - 678fc808-3192-4aaa-bb1d-51b51659ec00
description: Edlef Romeny. A Dutch/Swedish artist who lived and painted in Provence.
author: Marco Romeny
email: marco@mimecom.net
