site_title: Edlef Romeny
menu:
  - title: First Selection
    href: /selected-july-2025
  - title: Not for Sale
    href: /nfs
  - title: Bio
    href: /bio
  - title: '[[ All Works ]]'
    href: /_works
  - title: '[[ Rejected ]]'
    href: /rejected
sections:
  - type: collection
    title: Featured
    collection: front-page-featured
    show_title: false
    hidden: false
socials:
  - title: Instagram
    href: https://www.instagram.com/atelierromeny/
copyright: The Estate of Edlef Romeny
ga: ''
css: ''
js: ''
collections:
  - 678fc808-3192-4aaa-bb1d-51b51659ec00
description: Edlef Romeny. A Dutch/Swedish artist who lived and painted in Provence.
author: Marco Romeny
email: marco@mimecom.net
