site_title: Edlef Romeny
menu:
  - title: Bio
    href: /bio
  - title: About
    href: /about
  - title: Paintings
    href: /selected-paintings
  - title: Prints
    href: /selected-prints
  - title: SEARCH
    href: /search
sections:
  - type: image
    title: Image
    show_title: false
    hidden: false
    image: /src/media/assets/Edlef While Painting.webp
    caption: ''
    href: ''
barrier:
  enabled: false
  password: edlef
  days: 7
  text: |-
    _A Dutchman who painted his way from Antwerp to Stockholm to the Luberon, and never stopped looking for colour..._ 

    _Questions? Ask_ [_Marco_](mailto:marco@atelierromeny.com)
socials:
  - title: '@atelierromeny'
    href: https://www.instagram.com/atelierromeny/
  - title: 'Inquiries: Marco Romeny'
    href: mailto:marco@atelierromeny.com
copyright: The Estate of Edlef Romeny
ga: G-T3WYVEPH4Q
css: ''
js: ''
collections:
  - 678fc808-3192-4aaa-bb1d-51b51659ec00
description: Edlef Romeny. A Dutch/Swedish artist who lived and painted in Provence.
share_image: /src/media/works/127-la-serviette-bleue-v2.webp
author: Marco Romeny
email: marco@mimecom.net
