backend:
  name: github
  repo: "mimecine/dev.atelierromeny.com" # The GitHub repository where the content will be stored
  branch: main

media_folder: "src/media/img"
public_folder: "/src/media/img"

collections:
  - name: "works"
    label: "Works"
    folder: "src/content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string", required: false }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Categories", name: "categories", widget: "string", required: false }
      - { label: "Width", name: "w", widget: "number", required: false }
      - { label: "Height", name: "h", widget: "number", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Note", name: "note", widget: "text", required: false }
      - { label: "File", name: "file", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Year Start", name: "year_start", widget: "number", required: false }
      - { label: "Year End", name: "year_end", widget: "number", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }